### ISSUE TITLE
Switch to 20.04 as ubuntu base

### ISSUE THREAD

**Issue by elupus** [rabits/dockerfiles#8]
18.04 is going to end up eol later this year and is quite old by now. would be nice to get a 20.04 base instead.

**Comment by rabits** [comment]
Hi, sorry but not sure I would spend time on supporting the 5* images anymore. Anyway it's quite easy to build them yourself - just update the Dockerfile to the ubuntu version you want and follow the README build instructions.

For the further activity I'm actually switching to Qt 6.2 since it's already looks quite good (https://github.com/state-of-the-art/qt6-docker , https://hub.docker.com/r/stateoftheartio/qt6 ) - that will be great if you can check them.
